name: hyperfine benchmarking
description: "Runs hyperfine benchmarking across provided input files"
author: "Blayne Chard <blayne@chard.com>"
inputs:
  benchmark-config:
    description: Benchmark file
    default: ".hyperfine.json"
  benchmark-output:
    description: Benchmark file
    default: "benchmarks.json"
  benchmark-html:
    description: Benchmark file
    default: "benchmarks.html"
  count:
    description: Number of past runs to keep (`0` keeps everything)
    default: "500"
  benchmark-branch:
    description: "Branch to use for benchmarks"
    required: false
    default: "gh-pages"
  github-token:
    description: Token to use to add comments to pull requests
    default: ${{ github.token }}
  master-branch:
    description: Branch to use as a base for benchmarks
    default: "master"
runs:
  using: "node20"
  main: "./dist/action.cjs"
