name: Main
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: linz/action-typescript@v3
      with: 
        node-version: 20

    - name: Bundle
      run: npm run bundle


