name: Main
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: linz/action-typescript@v3

    - name: Bundle
      run: npm run bundle

    - name: Test Action
      uses: ./

